spring:
    datasource:
      url: postgres://ezqlphpdtvfzyr:9bf1e9fa6d372ff2ac2b858adddf3ddd0239748a690bd006e915d60fef522af3@ec2-46-137-170-51.eu-west-1.compute.amazonaws.com:5432/d7evlvi2miks14
        username: ezqlphpdtvfzyr
        password: 9bf1e9fa6d372ff2ac2b858adddf3ddd0239748a690bd006e915d60fef522af3


server:
  port: $PORT
    maxHttpHeaderSize: 102400
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
        min-response-size: 1024


