spring:
<<<<<<< HEAD
    datasource:
        url: ${JDBC_DATABASE_URL}
        username: ${JDBC_DATABASE_USERNAME}
        password: ${JDBC_DATABASE_PASSWORD}

=======
  datasource:
    url: postgres://imdymmkgrsewnw:40d207047514aba48b941751f7a0bd9821991f1dbade649a99a4a87bc1aa97cf@ec2-46-137-170-51.eu-west-1.compute.amazonaws.com:5432/daurq08uj5jss7
    username: imdymmkgrsewnw
    password: 40d207047514aba48b941751f7a0bd9821991f1dbade649a99a4a87bc1aa97cf
>>>>>>> 99262251ebad995d6a71dcb96f11935e5b60037a
    jpa:
        show-sql: false
        hibernate:
          ddl-auto: update
          naming:
            implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
<<<<<<< HEAD
        spring:
          jpa:
            properties:
              hibernate:
                jdbc:
                  lob:
                    non_contextual_creation: true
            database-platform: org.hibernate.dialect.PostgreSQL9Dialect
=======
server:
  port: 5432
    maxHttpHeaderSize: 102400
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
        min-response-size: 1024


>>>>>>> 99262251ebad995d6a71dcb96f11935e5b60037a
